# Generated by Django 6.0.7 on 2026-09-03 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_payroll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='month',
            field=models.DateField(max_length=7),
        ),
    ]
